# Generated by Django 5.2.1 on 2025-05-27 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('Su', 'Suet'), ('Se', 'Seeds'), ('F', 'Fruit'), ('B', 'Berries'), ('I', 'Insects'), ('O', 'Other')], default='Su', max_length=2)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bird')),
            ],
        ),
    ]
